# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectVK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectVK
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.5.0'
  pod 'RealmSwift', '~> 3.15.0'

end
